### ISSUE TITLE
After update Admin panel is not accessible 

### ISSUE THREAD

**Issue by yapka-apple** [YunoHost-Apps/castopod_ynh#74] opened 2022-07-23 13:05 UTC
### Describe the bug

After the last update can longer get to admin page. Get 404 not found. On all three of my Castopod installs. 

### Context

- Hardware: *Linode VPS, 4 core, 8gb ram*
- YunoHost version: 11.0.7
- I have access to my server: *Access through ssh or Linode lish console*
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: *no *
  - If yes, please explain:

### Steps to reproduce

You can check out one of my blogs.. https://noexpectations.show/@noexpectations/cp-admin

### Expected behavior

*I should get admin panel login*

**Comment by navanchauhan** [comment] 2022-07-23 13:44
https://noexpectations.show/@noexpectations/cp-admin is the incorrect URL

Try https://noexpectations.show/@noexpectations/cp-admin

**Comment by yapka-apple** [comment] 2022-07-23 14:03
This is resolved, not sure what happened but I put in my address as `https://mydomain//cp-admin` and it brought me back to login page. Everything worked as normal from there.

**Comment by navanchauhan** [comment] 2022-07-23 15:55
Thanks for reopening the issue. I want to investigate why this was happening. 

Also, you don't need `//` in the end, just `https://mydomain/cp-admin` should work

**Comment by DDRrayray2012** [comment] 2022-07-24 16:05
my instance is at [ddrpodcast.com](url)

**Comment by navanchauhan** [comment] 2022-07-24 16:31
> my instance is at [ddrpodcast.com](url)

I can see the CP-Admin panel at [https://ddrpodcast.com/cp-admin](https://ddrpodcast.com/cp-admin), but you are right the main page does show `Whoops!` which shouldn't happen

While I investiage this issue, you can restore the app to the previous version (before the upgrade) and use it normally. Let me know if you need help restoring to the previous version

**Comment by ericgaspar** [comment] 2022-07-24 16:44
It might be interesting to know from which version you have updated Castopod. (The datbase structure get modifies sometime from one version to the next...).

**Comment by DDRrayray2012** [comment] 2022-07-24 16:59
The issue originally popped up when upgrading from 1.0.0-96-ynh1 to 1.0.0-98-ynh2.  I restored back to 1.0.0-96-ynh1 and then upgraded to 1.0.0-99~ynh1 and the same issue occurred.  I have now restored back to 1.0.0-96-ynh1.

**Comment by DDRrayray2012** [comment] 2022-07-24 19:20
My server info is as follows:
Hardware: Raspberry Pi 3B
YunoHost version: 4.3.6.3
I have access to my server : Through SSH | through the webadmin | direct access via keyboard / screen | …
Are you in a special context or did you perform some particular tweaking on your YunoHost instance ? : no

**Comment by demitasse-1** [comment] 2022-07-26 18:55
Having the same issue, after upgrading my instance only shows the whoops hit a snag image, for admin and for the public facing site for my podcast. 

I can login to the admin but only see whoops hit a snag. I also had the problem when upgrading from  1.0.0-96-ynh1 to 1.0.0-98-ynh2 and from 1.0.0-98-ynh2 to 1.0.0-99~ynh1. Using Yunohost version  4.3.6.3 (stable) on a VPS. 

I can restore back to 1.0.0-96-ynh1 but my latest episode was not uploaded for that back up, and my latest episode still seems to be accessible via RSS for podcast apps and such.

**Comment by navanchauhan** [comment] 2022-07-26 21:02
Looks like we need to run this for upgrading from beta.16 https://code.castopod.org/adaures/castopod/-/tags/v1.0.0-beta.17#update-instructions


```sql
SET AUTOCOMMIT = 0;
START TRANSACTION;

ALTER TABLE `cp_settings`
ADD COLUMN context VARCHAR(255) NULL AFTER `type`;

ALTER TABLE cp_podcasts ADD COLUMN published_at DATETIME DEFAULT NULL AFTER updated_by;
UPDATE cp_podcasts SET published_at = created_at;

COMMIT;
```

@ericgaspar do you want me to add this fix to the upgrade script? (with a version check)

**Comment by ericgaspar** [comment] 2022-07-26 21:26
> @ericgaspar do you want me to add this fix to the upgrade script? (with a version check)

@navanchauhan If you have the time, it will be greatly appreciated.

**Comment by navanchauhan** [comment] 2022-07-26 21:56
@DDRrayray2012 @demitasse-1  

I was able to reproduce your errors and fix it. Should be fixed by #75

**Comment by DDRrayray2012** [comment] 2022-07-26 22:21
Awesome.   I’ll apply the update as soon as its available.   Thanks to everyone who helped identify and fix this!

**Closed** 2022-07-27 06:39 UTC

**Comment by mattbk** [comment] 2022-08-26 02:04
I ran into this too, but didn't restore from backup. I just installed phpmyadmin and ran the SQL at https://github.com/YunoHost-Apps/castopod_ynh/blob/75952d20abc6b900809c442712a0bf39acc5d8d4/scripts/from_beta_16.sql. Seems to have fixed the problem as designed, thanks!

For anyone else searching based on log entries, this is what I had:
```
ERROR - 2022-08-25 15:15:03 --> Unknown column 'cp_podcasts.published_at' in 'where clause'
CRITICAL - 2022-08-25 15:15:03 --> Call to a member function getResult() on bool
in SYSTEMPATH/Model.php on line 223.
 1 SYSTEMPATH/BaseModel.php(584): CodeIgniter\Model->doFindAll()
 2 ROOTPATH/modules/WebSub/Controllers/WebSubController.php(40): CodeIgniter\BaseModel->findAll()
 3 SYSTEMPATH/CodeIgniter.php(896): Modules\WebSub\Controllers\WebSubController->publish()
 4 SYSTEMPATH/CodeIgniter.php(466): CodeIgniter\CodeIgniter->runController()
 5 SYSTEMPATH/CodeIgniter.php(349): CodeIgniter\CodeIgniter->handleRequest()
 6 FCPATH/index.php(61): CodeIgniter\CodeIgniter->run()
ERROR - 2022-08-25 15:15:03 --> Unknown column 'context' in 'where clause'
ERROR - 2022-08-25 15:15:04 --> Unknown column 'context' in 'where clause'
ERROR - 2022-08-25 15:15:07 --> Unknown column 'context' in 'where clause'
ERROR - 2022-08-25 15:15:10 --> Unknown column 'context' in 'where clause'
ERROR - 2022-08-25 15:15:13 --> Unknown column 'context' in 'where clause'
ERROR - 2022-08-25 15:15:16 --> Unknown column 'context' in 'where clause'
ERROR - 2022-08-25 15:15:18 --> Unknown column 'published_at' in 'where clause'
CRITICAL - 2022-08-25 15:15:18 --> Call to a member function getFirstRow() on bool
in SYSTEMPATH/Model.php on line 249.
```
